<?php
include 'header.php';
echo '<div align="center">';
echo '<p><form action="dashboard.php">';
echo '<button type="submit" style="width:524px; font-size:1.2em">>> Show Dashboard <<</button>';
echo '</form></p>';
echo '<table>';
echo '<tr>';
echo '<td>';
echo '<form action="menu_insert.php">';
echo '<div><button type="submit">Insert</button></div>';
echo '</form>';
echo '</td>';
echo '<td>';
echo '<form action="menu_delete.php">';
echo '<div><button type="submit">Delete</button></div>';
echo '</form>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td>';
echo '<form action="menu_update.php">';
echo '<div><button type="submit">Update</button></div>';
echo '</form>';
echo '</td>';
echo '<td>';
echo '<form action="listing.php">';
echo '<div><button type="submit">List All TV Shows</button></div>';
echo '</form>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td>';
echo '<form action="importkodidb.php">';
echo '<div><button type="submit">Import Kodi DB</button></div>';
echo '</form>';
echo '</td>';
echo '<td>';
echo '<form action="tools.php">';
echo '<div><button type="submit">Tools</button></div>';
echo '</form>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2">';
echo '<form action="help.php">';
echo '<div align="center"><button type="submit">Help</button></div>';
echo '</form>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</div>';
include 'footer.php';
?>
