<?php
include 'header.php';
echo '<div align="center">';
echo '<p><H2>Welcome to SkipDB Interface</h2></p>';
echo '<table>';
echo '<tr>';
echo '<td>';
echo '<form action="setup.php">';
echo '<div><button type="submit">Create Tables In Database</button></div>';
echo '</form>';
echo '</td>';
echo '<td>';
echo '<form action="check.php">';
echo '<div><button type="submit">Check SQL-Connect and Tables</button></div>';
echo '</form>';
echo '</td>';
echo '<tr>';
echo '<td>';
echo '<form action="checkjson.php">';
echo '<div><button type="submit">Check JSON-Interface</button></div>';
echo '</form>';
echo '</td>';
echo '<td>';
echo '<form action="clean.php">';
echo '<div><button type="submit">Clean SkipDB</button></div>';
echo '</form>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td>';
echo '<form action="updater.php">';
echo '<div><button type="submit">Online Update Interface</button></div>';
echo '</form>';
echo '</td>';
echo '</tr>';
echo '<table>';
echo '<form action="index.php">';
echo '<div><button type="submit">Home</button></div>';
echo '</form>';
echo '</div>';
include 'footer.php';
?>
